<?php
namespace app\index\controller;
/**
 * Created by PhpStorm.
 * User: imdante
 * Date: 2016/11/30
 * Time: 12:20
 */
use app\api\Api;
use app\api\Category;

class Lists extends Common {
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->assign('action',request()->action());
    }

    public function index(){
        $alias = htmlspecialchars(input('param.alias'));
        $id = htmlspecialchars(input('param.id'));
        $channel = Api::get_alias_catid($alias); //换取栏目分类id 并且验证是否存在
        $this->assign('channel',$channel);
        //分类
        $category = Category::category($channel['id']);
        $this->assign('category',$category);
        $material = self::lists($channel['id'],$id);
        $this->assign('list',$material);

        return $this->fetch();
    }

    public static function lists($cid=''){
        $data = db('article')->where('status',1)->order('id','desc')->cache(true,600)->paginate(25);
        return $data;
    }

    public function blog(){
        $list = self::lists();
        $this->assign('list',$list);

        return $this->fetch();
    }
    public function template(){
        return $this->fetch();
    }
    public function jquery(){
        return $this->fetch();
    }
    public function thinkphp(){
        return $this->fetch();
    }
    public function wenda(){
        return $this->fetch();
    }
    public function tools(){
        return $this->fetch();
    }
}